name: dnd_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    sdk: ^3.12.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.8
    shared_preferences: ^2.5.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/to/font-from-package
    assets:
        #icons

        - assets/icons/base/classes/barbarian.jpg
        - assets/icons/base/classes/bard.jpg
        - assets/icons/base/classes/cleric.jpg
        - assets/icons/base/classes/druid.jpg
        - assets/icons/base/classes/fighter.jpg
        - assets/icons/base/classes/monk.jpg
        - assets/icons/base/classes/paladin.jpg
        - assets/icons/base/classes/ranger.jpg
        - assets/icons/base/classes/rogue.jpg
        - assets/icons/base/classes/sorcerer.jpg
        - assets/icons/base/classes/warlock.jpg
        - assets/icons/base/classes/wizard.jpg
        - assets/icons/base/default.png
        - assets/icons/base/arrow-down.png

        #jsons

        - assets/json/classes.json
        - assets/json/spells.json
        - assets/json/feats.json
        - assets/json/species.json
        - assets/json/backgrounds.json
        - assets/json/categories.json

        #classes
        - assets/json/classes/barbarian.json

        - assets/json/classes/barbarian/berserker.json
        - assets/json/classes/barbarian/wild_heart.json
        - assets/json/classes/barbarian/world_tree.json
        - assets/json/classes/barbarian/zealot.json

        - assets/json/classes/bard.json
        - assets/json/classes/cleric.json
        - assets/json/classes/druid.json
        - assets/json/classes/fighter.json
        - assets/json/classes/monk.json
        - assets/json/classes/paladin.json
        - assets/json/classes/ranger.json
        - assets/json/classes/rogue.json
        - assets/json/classes/sorcerer.json
        - assets/json/classes/warlock.json
        - assets/json/classes/wizard.json
        - assets/json/species/aasimar.json

        #species
        - assets/json/species/aasimar.json
        - assets/json/species/dragonborn.json
        - assets/json/species/dwarf.json
        - assets/json/species/elf.json
        - assets/json/species/gnome.json
        - assets/json/species/goliath.json
        - assets/json/species/halfling.json
        - assets/json/species/human.json
        - assets/json/species/orc.json
        - assets/json/species/tiefling.json
        - assets/json/species/changeling.json
        - assets/json/species/kalashtar.json
        - assets/json/species/khoravar.json
        - assets/json/species/shifter.json
        - assets/json/species/warforged.json
        - assets/json/species/boggart.json
        - assets/json/species/faerie.json
        - assets/json/species/flamekin.json
        - assets/json/species/lorwyn.json
        - assets/json/species/changeling.json
        - assets/json/species/rimekin.json
        - assets/json/species/dhampir.json
        - assets/json/species/hexblood.json
        - assets/json/species/lupin.json
        - assets/json/species/reborn.json

        #backgrounds
        - assets/json/backgrounds/acolyte.json
        - assets/json/backgrounds/artisan.json
        - assets/json/backgrounds/charlatan.json
        - assets/json/backgrounds/criminal.json
        - assets/json/backgrounds/entertainer.json
        - assets/json/backgrounds/farmer.json
        - assets/json/backgrounds/guard.json
        - assets/json/backgrounds/guide.json
        - assets/json/backgrounds/hermit.json
        - assets/json/backgrounds/merchant.json
        - assets/json/backgrounds/noble.json
        - assets/json/backgrounds/sage.json
        - assets/json/backgrounds/sailor.json
        - assets/json/backgrounds/scribe.json
        - assets/json/backgrounds/soldier.json
        - assets/json/backgrounds/wayfarer.json
        - assets/json/backgrounds/aberrant-heir.json
        - assets/json/backgrounds/archaeologist.json
        - assets/json/backgrounds/house-agent.json
        - assets/json/backgrounds/house-cannith-heir.json
        - assets/json/backgrounds/house-deneith-heir.json
        - assets/json/backgrounds/house-ghallanda-heir.json
        - assets/json/backgrounds/house-jorasco-heir.json
        - assets/json/backgrounds/house-kundarak-heir.json
        - assets/json/backgrounds/house-lyrandar-heir.json
        - assets/json/backgrounds/house-medani-heir.json
        - assets/json/backgrounds/house-orien-heir.json
        - assets/json/backgrounds/house-phiarlan-heir.json
        - assets/json/backgrounds/house-sivis-heir.json
        - assets/json/backgrounds/house-tharashk-heir.json
        - assets/json/backgrounds/house-thuranni-heir.json
        - assets/json/backgrounds/house-vadalis-heir.json
        - assets/json/backgrounds/inquisitive.json
        - assets/json/backgrounds/chondathan-freebooter.json
        - assets/json/backgrounds/dead-magic-dweller.json
        - assets/json/backgrounds/dragon-cultist.json
        - assets/json/backgrounds/emerald-enclave-caretaker.json
        - assets/json/backgrounds/flaming-fist-mercenary.json
        - assets/json/backgrounds/genie-touched.json
        - assets/json/backgrounds/harper.json
        - assets/json/backgrounds/ice-fisher.json
        - assets/json/backgrounds/knight-of-the-gauntlet.json
        - assets/json/backgrounds/lords-alliance-vassal.json
        - assets/json/backgrounds/moonwell-pilgrim.json
        - assets/json/backgrounds/mulhorandi-tomb-raider.json
        - assets/json/backgrounds/mythalkeeper.json
        - assets/json/backgrounds/purple-dragon-squire.json
        - assets/json/backgrounds/rashemi-wanderer.json
        - assets/json/backgrounds/shadowmasters-exile.json
        - assets/json/backgrounds/spellfire-initiate.json
        - assets/json/backgrounds/zhentarim-mercenary.json
        - assets/json/backgrounds/haunted-one.json
        - assets/json/backgrounds/investigator.json
        - assets/json/backgrounds/mist-wanderer.json
        - assets/json/backgrounds/spirit-medium.json
        - assets/json/backgrounds/carouser.json
        - assets/json/backgrounds/lorwyn-expert.json
        - assets/json/backgrounds/pact-seeker.json
        - assets/json/backgrounds/shadowmoor-expert.json
        - assets/json/backgrounds/vampire-devotee.json
        - assets/json/backgrounds/vampire-survivor.json

        #feats
        - assets/json/feats/alert.json
        - assets/json/feats/crafter.json
        - assets/json/feats/healer.json
        - assets/json/feats/lucky.json
        - assets/json/feats/magic-initiate.json
        - assets/json/feats/musician.json
        - assets/json/feats/savage-attacker.json
        - assets/json/feats/sharp-eye.json
        - assets/json/feats/skilled.json
        - assets/json/feats/survivor.json
        - assets/json/feats/tavern-brawler.json
        - assets/json/feats/tough.json
        - assets/json/feats/cult-of-the-dragon-initiate.json
        - assets/json/feats/emerald-enclave-fledgling.json
        - assets/json/feats/harper-agent.json
        - assets/json/feats/lords-alliance-agent.json
        - assets/json/feats/purple-dragon-rook.json
        - assets/json/feats/spellfire-spark.json
        - assets/json/feats/tyro-of-the-gauntlet.json
        - assets/json/feats/zhentarim-ruffian.json
        - assets/json/feats/child-of-the-sun.json
        - assets/json/feats/shadowmoor-hexer.json
        - assets/json/feats/tireless-reveler.json
        - assets/json/feats/vampire-hunter.json
        - assets/json/feats/vampire-s-plaything.json
        - assets/json/feats/ability-score-improvement.json
        - assets/json/feats/actor.json
        - assets/json/feats/athlete.json
        - assets/json/feats/charger.json
        - assets/json/feats/chef.json
        - assets/json/feats/crossbow-expert.json
        - assets/json/feats/crusher.json
        - assets/json/feats/defensive-duelist.json
        - assets/json/feats/dual-wielder.json
        - assets/json/feats/durable.json
        - assets/json/feats/elemental-adept.json
        - assets/json/feats/fey-touched.json
        - assets/json/feats/grappler.json
        - assets/json/feats/great-weapon-master.json
        - assets/json/feats/heavily-armored.json
        - assets/json/feats/heavy-armor-master.json
        - assets/json/feats/inspiring-leader.json
        - assets/json/feats/keen-mind.json
        - assets/json/feats/lightly-armored.json
        - assets/json/feats/mage-slayer.json
        - assets/json/feats/martial-weapon-training.json
        - assets/json/feats/medium-armor-master.json
        - assets/json/feats/moderately-armored.json
        - assets/json/feats/mounted-combatant.json
        - assets/json/feats/observant.json
        - assets/json/feats/piercer.json
        - assets/json/feats/poisoner.json
        - assets/json/feats/polearm-master.json
        - assets/json/feats/resilient.json
        - assets/json/feats/ritual-caster.json
        - assets/json/feats/sentinel.json
        - assets/json/feats/shadow-touched.json
        - assets/json/feats/sharpshooter.json
        - assets/json/feats/shield-master.json
        - assets/json/feats/shifting-combatant.json
        - assets/json/feats/skill-expert.json
        - assets/json/feats/skulker.json
        - assets/json/feats/slasher.json
        - assets/json/feats/speedy.json
        - assets/json/feats/spell-sniper.json
        - assets/json/feats/tactical-combatant.json
        - assets/json/feats/telekinetic.json
        - assets/json/feats/telepathic.json
        - assets/json/feats/war-caster.json
        - assets/json/feats/weapon-master.json
        - assets/json/feats/cold-caster.json
        - assets/json/feats/dragonscarred.json
        - assets/json/feats/enclave-magic.json
        - assets/json/feats/fairy-trickster.json
        - assets/json/feats/genie-magic.json
        - assets/json/feats/harper-teamwork.json
        - assets/json/feats/lordly-resolve.json
        - assets/json/feats/mythal-touched.json
        - assets/json/feats/order-s-resilience.json
        - assets/json/feats/purple-dragon-commandant.json
        - assets/json/feats/spellfire-adept.json
        - assets/json/feats/street-justice.json
        - assets/json/feats/zhentarim-tactics.json
        - assets/json/feats/bloodlust.json
        - assets/json/feats/bomber.json
        - assets/json/feats/cloying-mists.json
        - assets/json/feats/delicious-pain.json
        - assets/json/feats/light-bringer.json
        - assets/json/feats/love-bites.json
        - assets/json/feats/putrefy.json
        - assets/json/feats/rebuke.json
        - assets/json/feats/treacherous-allure.json
        - assets/json/feats/vampire-touched.json
        - assets/json/feats/archery.json
        - assets/json/feats/blind-fighting.json
        - assets/json/feats/defense.json
        - assets/json/feats/dueling.json
        - assets/json/feats/great-weapon-fighting.json
        - assets/json/feats/interception.json
        - assets/json/feats/pack-fighting.json
        - assets/json/feats/prone-fighting.json
        - assets/json/feats/protection.json
        - assets/json/feats/thrown-weapon-fighting.json
        - assets/json/feats/two-weapon-fighting.json
        - assets/json/feats/unarmed-fighting.json
        - assets/json/feats/boon-of-combat-prowess.json
        - assets/json/feats/boon-of-dimensional-travel.json
        - assets/json/feats/boon-of-energy-resistance.json
        - assets/json/feats/boon-of-fate.json
        - assets/json/feats/boon-of-fortitude.json
        - assets/json/feats/boon-of-irresistible-offense.json
        - assets/json/feats/boon-of-recovery.json
        - assets/json/feats/boon-of-skill.json
        - assets/json/feats/boon-of-speed.json
        - assets/json/feats/boon-of-spell-recall.json
        - assets/json/feats/boon-of-the-night-spirit.json
        - assets/json/feats/boon-of-truesight.json
        - assets/json/feats/boon-of-siberys.json
        - assets/json/feats/boon-of-bloodshed.json
        - assets/json/feats/boon-of-bountiful-health.json
        - assets/json/feats/boon-of-communication.json
        - assets/json/feats/boon-of-desperate-resilience.json
        - assets/json/feats/boon-of-exquisite-radiance.json
        - assets/json/feats/boon-of-fluid-forms.json
        - assets/json/feats/boon-of-fortune-s-favor.json
        - assets/json/feats/boon-of-poison-mastery.json
        - assets/json/feats/boon-of-revelry.json
        - assets/json/feats/boon-of-terror.json
        - assets/json/feats/boon-of-the-bright-sun.json
        - assets/json/feats/boon-of-the-furious-storm.json
        - assets/json/feats/boon-of-the-soul-drinker.json
        - assets/json/feats/boon-of-blazing-dawn.json
        - assets/json/feats/boon-of-looming-shadows.json
        - assets/json/feats/boon-of-misty-escape.json
        - assets/json/feats/aberrant-dragonmark.json
        - assets/json/feats/mark-of-detection.json
        - assets/json/feats/mark-of-finding.json
        - assets/json/feats/mark-of-handling.json
        - assets/json/feats/mark-of-healing.json
        - assets/json/feats/mark-of-hospitality.json
        - assets/json/feats/mark-of-making.json
        - assets/json/feats/mark-of-passage.json
        - assets/json/feats/mark-of-scribing.json
        - assets/json/feats/mark-of-sentinel.json
        - assets/json/feats/mark-of-shadow.json
        - assets/json/feats/mark-of-storm.json
        - assets/json/feats/mark-of-warding.json
        - assets/json/feats/greater-aberrant-mark.json
        - assets/json/feats/greater-mark-of-detection.json
        - assets/json/feats/greater-mark-of-finding.json
        - assets/json/feats/greater-mark-of-handling.json
        - assets/json/feats/greater-mark-of-healing.json
        - assets/json/feats/greater-mark-of-hospitality.json
        - assets/json/feats/greater-mark-of-making.json
        - assets/json/feats/greater-mark-of-passage.json
        - assets/json/feats/greater-mark-of-scribing.json
        - assets/json/feats/greater-mark-of-sentinel.json
        - assets/json/feats/greater-mark-of-shadow.json
        - assets/json/feats/greater-mark-of-storm.json
        - assets/json/feats/greater-mark-of-warding.json
        - assets/json/feats/potent-dragonmark.json
        - assets/json/feats/fey-pact.json
        - assets/json/feats/infernal-pact.json
        - assets/json/feats/fey-sentinel.json
        - assets/json/feats/fey-tormentor.json
        - assets/json/feats/infernal-bulwark.json
        - assets/json/feats/infernal-dragoon.json
        - assets/json/feats/aberrant-anatomy.json
        - assets/json/feats/echoing-soul.json
        - assets/json/feats/gathered-whispers.json
        - assets/json/feats/living-shadow.json
        - assets/json/feats/mist-walker.json
        - assets/json/feats/second-skin.json
        - assets/json/feats/symbiotic-being.json
        - assets/json/feats/touch-of-death.json
        - assets/json/feats/watchers.json
        - assets/json/feats/origin.json
        - assets/json/feats/general.json
        - assets/json/feats/fightingStyle.json
        - assets/json/feats/epicBoon.json
        - assets/json/feats/dragonmark.json
        - assets/json/feats/planarPact.json
        - assets/json/feats/darkGift.json
        - assets/json/feats.json

        #other
        - assets/json/other/weaponMastery.json
