"""
dnd2024_scraper.py

Scrapes class + subclass pages from http://dnd2024.wikidot.com and produces
JSON matching the shape of the hand-authored example (Barbarian) you gave me:

    {id, catId, name, icon, hitDie, savingThrows, casterLevel,
     spellcastingAbility, attacksPerLevel, proficiencies, startingEquipment,
     features: [{name, level, description}, ...],
     archetypes: [{name, features:[...]}]}

DESIGN NOTES (read before trusting the output blindly)
--------------------------------------------------------
Every D&D-2024-wikidot page uses the same skeleton:

    <div id="page-title">Barbarian</div>
    <div id="page-content">
        ... h1/h2/h3/h5/h6 headings, <p>, <ul>/<ol>, <table> ...
    </div>

That much I'm confident about -- it's standard Wikidot, and your original
script already confirmed `#page-content` resolves. Everything below walks
`#page-content` by TAG NAME ONLY (h1..h6, p, ul, ol, table) -- I deliberately
avoid depending on guessed CSS class names (e.g. "wiki-content-table"),
because I can't verify those against raw HTML from here (my fetch tool only
gives me a cleaned/markdown view of pages, not raw source -- I don't have
live network access in this sandbox to run `requests` myself). Tag-name-only
walking is much more robust to theme/markup details I can't see.

A few fields in your target schema simply AREN'T present on the wiki page in
that shape, so they're generated by convention / heuristic rather than
scraped. These are flagged clearly below and you should sanity-check them:

  - id / catId      : auto-numbered "c1", "c2", ... + hardcoded "class"
  - icon.base        : generated as assets/icons/base/classes/<slug>.jpg
  - casterLevel      : guessed from a full/half caster lookup table
  - spellcastingAbility: parsed from "<Ability> is your spellcasting
                          ability" if present, else defaults to "Int"
                          (matching what your Barbarian example does for a
                          non-caster)
  - attacksPerLevel  : derived by scanning for "Extra Attack" features and
                        bumping the count each time it's granted (this
                        matches Barbarian's {"1":1,"5":2} exactly, and also
                        handles Fighter, who gets it 3 times)

Everything else (name, hitDie, savingThrows, proficiencies,
startingEquipment, features, archetypes) is scraped directly.

WHY I HAVEN'T VALIDATED THIS AGAINST THE LIVE SITE
---------------------------------------------------
My sandbox has no outbound network access for code execution, and my web
browsing tool returns cleaned text, not raw HTML -- so I can't run this
script against the real site myself. I *did* fetch the cleaned content of
the Barbarian, Wizard, and class-list pages to design this around the real
content/structure, and I unit-tested every parsing helper against synthetic
HTML built to match that structure (see test block at the bottom, run with
`python3 dnd2024_scraper.py --selftest`). But the very first real run is a
good moment to pass `--class barbarian` and diff the output against your
known-good Barbarian JSON before scraping all 13 classes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from typing import Optional

import requests
from bs4 import BeautifulSoup, Tag

BASE_URL = "http://dnd2024.wikidot.com"
CLASS_LIST_URL = f"{BASE_URL}/class:all"
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; dnd2024-json-export/1.0)"}
REQUEST_DELAY = 0.6

ABILITY_ABBR = {
    "strength": "Str", "dexterity": "Dex", "constitution": "Con",
    "intelligence": "Int", "wisdom": "Wis", "charisma": "Cha",
}

FULL_CASTERS = {"bard", "cleric", "druid", "sorcerer", "warlock", "wizard"}
HALF_CASTERS = {"paladin", "ranger", "artificer"}

LEVEL_HEADER_RE = re.compile(r"^\s*Level\s+(\d+)\s*:\s*(.+?)\s*$", re.IGNORECASE)
CURRENCY_RE = re.compile(r"^\d+\s*(GP|SP|CP|EP|PP)$", re.IGNORECASE)

IRREGULAR_SINGULARS = {
    "handaxes": "Handaxe",
    "javelins": "Javelin",
    "daggers": "Dagger",
    "darts": "Dart",
    "knives": "Knife",
    "torches": "Torch",
}


# --------------------------------------------------------------------------
# Fetching
# --------------------------------------------------------------------------

def fetch_soup(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def get_page_content(soup: BeautifulSoup) -> Tag:
    pc = soup.find(id="page-content")
    if pc is None:
        raise ValueError("Could not find div#page-content on this page")
    return pc


def get_page_title(soup: BeautifulSoup) -> str:
    title_div = soup.find(id="page-title")
    if title_div is not None:
        return title_div.get_text(strip=True)
    if soup.title:
        return re.sub(r"\s*-\s*D&D 5e \(2024\)\s*$", "", soup.title.get_text())
    return "Unknown"


def clean_text(el: Tag) -> str:
    return el.get_text(" ", strip=True)


# --------------------------------------------------------------------------
# Table classification + parsing
# --------------------------------------------------------------------------
# Only three table shapes appear on these pages: a title+key/value "traits"
# table, the big multi-column level-progression table, and a single-column
# "Name" table listing subclasses. We never depend on a CSS class to tell
# them apart -- just row/column shape.

def classify_table(table: Tag):
    rows = table.find_all("tr")
    if not rows:
        return "unknown", rows
    header_cells = rows[0].find_all(["th", "td"])
    header_texts = [clean_text(c) for c in header_cells]
    if header_texts and header_texts[0].strip().lower() == "level":
        return "progression", rows
    if len(header_texts) == 1 and header_texts[0].strip().lower() == "name":
        return "sublist", rows
    return "traits", rows


def parse_traits_table(rows) -> dict:
    traits = {}
    for row in rows[1:]:
        cells = row.find_all(["th", "td"])
        if len(cells) >= 2:
            label = clean_text(cells[0])
            value = clean_text(cells[1])
            traits[label] = value
    return traits


def parse_sublist_table(rows, base_url: str) -> list[tuple[str, str]]:
    out = []
    for row in rows[1:]:
        link = row.find("a")
        if link and link.get("href"):
            name = clean_text(link)
            href = link["href"]
            if href.startswith("/"):
                href = base_url.rstrip("/") + href
            elif not href.startswith("http"):
                href = base_url.rstrip("/") + "/" + href
            out.append((name, href))
    return out


# --------------------------------------------------------------------------
# Text field parsers (Core Traits table values -> structured schema pieces)
# --------------------------------------------------------------------------

def parse_hit_die(text: str) -> str:
    m = re.search(r"[Dd](\d+)", text)
    return f"d{m.group(1)}" if m else text


def parse_saving_throws(text: str) -> list[str]:
    parts = re.split(r",\s*and\s+|,\s*|\s+and\s+", text.strip())
    out = []
    for p in parts:
        key = p.strip().lower()
        if key in ABILITY_ABBR:
            out.append(ABILITY_ABBR[key])
    return out


def split_or_list(text: str) -> list[str]:
    text = text.rstrip(".").strip()
    # ", or " must be tried before a bare "," so "X, or Y" splits cleanly
    parts = re.split(r",\s*or\s+|,\s*|\s+or\s+", text)
    return [p.strip() for p in parts if p.strip()]


def parse_skill_choice(text: str) -> tuple[Optional[int], list[str]]:
    m = re.search(r"Choose\s+(\d+)\s*:\s*(.+)", text, re.IGNORECASE)
    if not m:
        return None, split_or_list(text)
    return int(m.group(1)), split_or_list(m.group(2))


def parse_weapon_profs(text: str) -> list[str]:
    text = text.strip()
    if text.lower() == "none":
        return []
    text = re.sub(r"\s+weapons?\s*$", "", text, flags=re.IGNORECASE)
    parts = re.split(r",\s*and\s+|,\s*|\s+and\s+", text)
    return [p.strip() for p in parts if p.strip()]


def parse_armor_profs(text: str) -> list[str]:
    text = text.strip()
    if text.lower() == "none":
        return []
    out = []
    for kw in ("Light", "Medium", "Heavy"):
        if re.search(rf"\b{kw}\b", text, re.IGNORECASE):
            out.append(kw)
    if re.search(r"\bShields?\b", text, re.IGNORECASE):
        out.append("Shields")
    return out


def singularize(word: str) -> str:
    key = word.lower()
    if key in IRREGULAR_SINGULARS:
        return IRREGULAR_SINGULARS[key]
    if key.endswith("axes"):
        return word[:-1]                    # Handaxes -> Handaxe
    if key.endswith("ies"):
        return word[:-3] + "y"              # Companies -> Company
    if key.endswith("ves"):
        return word[:-3] + "fe"             # Knives -> Knife
    if re.search(r"(ches|shes|xes|ses|zes)$", key):
        return word[:-2]                    # Boxes -> Box
    if key.endswith("s") and not key.endswith("ss"):
        return word[:-1]                    # Daggers -> Dagger
    return word


def expand_quantity(item: str) -> list[str]:
    item = item.strip()
    if CURRENCY_RE.match(item):
        return [item]                       # "15 GP" stays as one entry
    m = re.match(r"^(\d+)\s+(.+)$", item)
    if m:
        qty, name = int(m.group(1)), singularize(m.group(2))
        return [name] * qty
    return [item] if item else []


def split_item_list(text: str) -> list[str]:
    text = text.replace(", and ", ", ").replace(" and ", ", ")
    parts = [p.strip().rstrip(".") for p in text.split(",")]
    return [p for p in parts if p]


def parse_starting_equipment(text: str) -> list[list[str]]:
    text = re.sub(r"^Choose[^:]*:\s*", "", text.strip())
    chunks = re.split(r";\s*or\s*", text)
    result = []
    for chunk in chunks:
        m = re.match(r"^\(([A-Z])\)\s*(.+)$", chunk.strip())
        content = m.group(2) if m else chunk.strip()
        items = split_item_list(content)
        expanded = []
        for it in items:
            expanded.extend(expand_quantity(it))
        if expanded:
            result.append(expanded)
    return result


# --------------------------------------------------------------------------
# Walking #page-content to pull out features + subclass links
# --------------------------------------------------------------------------

def is_page_tags_marker(el: Tag) -> bool:
    """Wikidot's per-page tag links (e.g. '[class]', '[subclass]') sit at
    the end of page-content. We treat hitting one as end-of-content so it
    doesn't get glued onto the last feature's description."""
    a_tags = el.find_all("a") if el.name != "a" else [el]
    return any("page-tags" in (a.get("href") or "") for a in a_tags)


def walk_page_content(page_content: Tag, base_url: str):
    """Returns (traits_dict, features_list, subclass_links_list)."""
    traits: dict = {}
    features: list = []
    subclass_links: list = []
    current: Optional[dict] = None

    relevant_tags = ["h1", "h2", "h3", "h4", "h5", "h6", "p", "ul", "ol", "table"]
    # Nested-in-table elements are dropped: tables are handled as a whole
    # when we hit the <table> tag itself, so their inner <p>/<li> shouldn't
    # also be walked as page-level paragraphs.
    elements = [el for el in page_content.find_all(relevant_tags, recursive=True)
                if el.find_parent("table") is None]
    n = len(elements)

    i = 0
    while i < n:
        el = elements[i]

        if el.name == "table":
            kind, rows = classify_table(el)
            if kind == "traits":
                traits.update(parse_traits_table(rows))
            elif kind == "sublist":
                subclass_links.extend(parse_sublist_table(rows, base_url))
            # "progression" tables are intentionally skipped: nothing in the
            # target schema is derived from them directly.
            i += 1
            continue

        if el.name == "p" and is_page_tags_marker(el):
            break  # end of real content

        if el.name in ("h1", "h2", "h3", "h4", "h5", "h6"):
            text = clean_text(el)
            m = LEVEL_HEADER_RE.match(text)
            if el.name == "h3" and m:
                current = {"name": m.group(2), "level": int(m.group(1)), "description": []}
                features.append(current)
                i += 1
                continue
            # Any other heading (h1/h2/h4/h5/h6) that shows up *inside* a
            # feature's span (e.g. Wizard's "Copying a Spell into the Book")
            # is folded into that feature's description as another line --
            # UNLESS it's immediately followed by a table, in which case
            # it's just that table's caption (e.g. "Barbarian Subclasses",
            # "Barbarian Features") and shouldn't appear as prose.
            next_is_table = (i + 1 < n and elements[i + 1].name == "table")
            if current is not None and text and not next_is_table:
                current["description"].append(text)
            i += 1
            continue

        if el.name in ("ul", "ol"):
            if current is not None:
                for li in el.find_all("li", recursive=False):
                    txt = clean_text(li)
                    if txt:
                        current["description"].append(txt)
            i += 1
            continue

        if el.name == "p":
            txt = clean_text(el)
            if current is not None and txt:
                current["description"].append(txt)
            i += 1
            continue

        i += 1

    for f in features:
        f["description"] = "\n".join(f["description"])

    return traits, features, subclass_links


# --------------------------------------------------------------------------
# Derived fields
# --------------------------------------------------------------------------

def compute_attacks_per_level(features: list) -> dict:
    result = {"1": 1}
    count = 1
    for feat in sorted(features, key=lambda f: f["level"]):
        if feat["name"].strip().lower() == "extra attack":
            count += 1
            result[str(feat["level"])] = count
    return result


def detect_spellcasting_ability(features: list) -> tuple[str, bool]:
    for feat in features:
        m = re.search(
            r"\b(Intelligence|Wisdom|Charisma)\b\s+is your spellcasting ability",
            feat["description"],
        )
        if m:
            return ABILITY_ABBR[m.group(1).lower()], True
    return "Int", False  # default mirrors the non-caster convention in your example


def guess_caster_level(slug: str, has_spellcasting: bool) -> float:
    if not has_spellcasting:
        return 0
    if slug in FULL_CASTERS:
        return 1
    if slug in HALF_CASTERS:
        return 0.5
    return 1  # unclassified caster (e.g. a UA/experimental class) -- verify manually


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


# --------------------------------------------------------------------------
# Top-level page parsers
# --------------------------------------------------------------------------

def parse_subclass_page(url: str, name_hint: Optional[str] = None) -> dict:
    soup = fetch_soup(url)
    pc = get_page_content(soup)
    _traits, features, _sub = walk_page_content(pc, BASE_URL)
    name = name_hint or get_page_title(soup)
    return {
        "name": name,
        "features": [
            {"name": f["name"], "level": f["level"], "description": f["description"]}
            for f in features
        ],
    }


def parse_class_page(url: str, class_index: int, fetch_subclasses: bool = True) -> dict:
    soup = fetch_soup(url)
    pc = get_page_content(soup)
    name = get_page_title(soup)
    slug = slugify(name)

    traits, features, subclass_links = walk_page_content(pc, BASE_URL)

    proficiencies = []
    if "Skill Proficiencies" in traits:
        options, skills = parse_skill_choice(traits["Skill Proficiencies"])
        entry = {"name": "Skill", "proficiencies": skills}
        if options is not None:
            entry = {"name": "Skill", "options": options, "proficiencies": skills}
        proficiencies.append(entry)
    if "Armor Training" in traits:
        proficiencies.append({"name": "Armor", "proficiencies": parse_armor_profs(traits["Armor Training"])})
    if "Weapon Proficiencies" in traits:
        proficiencies.append({"name": "Weapon", "proficiencies": parse_weapon_profs(traits["Weapon Proficiencies"])})
    if "Tool Proficiencies" in traits:
        proficiencies.append({"name": "Tool", "proficiencies": split_or_list(traits["Tool Proficiencies"])})

    starting_equipment = []
    if "Starting Equipment" in traits:
        starting_equipment = parse_starting_equipment(traits["Starting Equipment"])

    spellcasting_ability, has_spellcasting = detect_spellcasting_ability(features)

    class_json = {
        "id": f"c{class_index}",
        "catId": "class",
        "name": name,
        "icon": {"base": f"assets/icons/base/classes/{slug}.jpg"},
        "hitDie": parse_hit_die(traits.get("Hit Point Die", "")),
        "savingThrows": parse_saving_throws(traits.get("Saving Throw Proficiencies", "")),
        "casterLevel": guess_caster_level(slug, has_spellcasting),
        "spellcastingAbility": spellcasting_ability,
        "attacksPerLevel": compute_attacks_per_level(features),
        "proficiencies": proficiencies,
        "startingEquipment": starting_equipment,
        "features": [
            {"name": f["name"], "level": f["level"], "description": f["description"]}
            for f in features
        ],
        "archetypes": [],
    }

    if fetch_subclasses:
        seen_urls = set()
        for sub_name, sub_url in subclass_links:
            if sub_url in seen_urls:
                continue
            seen_urls.add(sub_url)
            time.sleep(REQUEST_DELAY)
            try:
                class_json["archetypes"].append(parse_subclass_page(sub_url, name_hint=sub_name))
            except Exception as exc:  # noqa: BLE001
                print(f"  ! failed to parse subclass {sub_name} ({sub_url}): {exc}", file=sys.stderr)

    return class_json


def discover_core_classes() -> list[tuple[str, str]]:
    """Returns [(name, url), ...] for core classes only (filters out the
    UA/experimental variants, which don't use the `:main` URL suffix)."""
    soup = fetch_soup(CLASS_LIST_URL)
    pc = get_page_content(soup)
    out = []
    for a in pc.find_all("a"):
        href = a.get("href") or ""
        if href.rstrip("/").endswith(":main"):
            name = clean_text(a)
            url = href if href.startswith("http") else BASE_URL + href
            out.append((name, url))
    return out


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Scrape dnd2024.wikidot.com classes to JSON")
    ap.add_argument("--class", dest="class_slug", help="only scrape one class, e.g. 'barbarian'")
    ap.add_argument("--outdir", default="output", help="directory to write JSON files to")
    ap.add_argument("--no-subclasses", action="store_true", help="skip fetching subclass pages")
    ap.add_argument("--selftest", action="store_true", help="run offline parser unit tests and exit")
    args = ap.parse_args()

    if args.selftest:
        run_selftests()
        return

    import os
    os.makedirs(args.outdir, exist_ok=True)

    classes = discover_core_classes()
    if args.class_slug:
        classes = [(n, u) for n, u in classes if slugify(n) == args.class_slug]
        if not classes:
            print(f"No class found matching slug '{args.class_slug}'", file=sys.stderr)
            sys.exit(1)

    all_classes = []
    for i, (name, url) in enumerate(classes, start=1):
        print(f"[{i}/{len(classes)}] {name} -> {url}")
        time.sleep(REQUEST_DELAY)
        try:
            data = parse_class_page(url, i, fetch_subclasses=not args.no_subclasses)
        except Exception as exc:  # noqa: BLE001
            print(f"  ! failed: {exc}", file=sys.stderr)
            continue
        all_classes.append(data)
        out_path = os.path.join(args.outdir, f"{slugify(name)}.json")
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"  -> wrote {out_path} ({len(data['features'])} features, {len(data['archetypes'])} archetypes)")

    combined_path = os.path.join(args.outdir, "all_classes.json")
    with open(combined_path, "w", encoding="utf-8") as f:
        json.dump(all_classes, f, indent=2, ensure_ascii=False)
    print(f"\nWrote {combined_path} with {len(all_classes)} classes")


# --------------------------------------------------------------------------
# Offline self-tests -- exercise every parsing helper against synthetic
# HTML built to mirror the real page structure, without needing the network.
# --------------------------------------------------------------------------

SAMPLE_CLASS_HTML = """
<html><body>
<div id="page-title">Barbarian</div>
<div id="page-content">
<p>Barbarians are mighty warriors...</p>
<table>
<tr><th>Core Barbarian Traits</th></tr>
<tr><td>Primary Ability</td><td>Strength</td></tr>
<tr><td>Hit Point Die</td><td>D12 per Barbarian level</td></tr>
<tr><td>Saving Throw Proficiencies</td><td>Strength and Constitution</td></tr>
<tr><td>Skill Proficiencies</td><td>Choose 2: Animal Handling, Athletics, Intimidation, Nature, Perception, or Survival</td></tr>
<tr><td>Weapon Proficiencies</td><td>Simple and Martial weapons</td></tr>
<tr><td>Armor Training</td><td>Light and Medium armor and Shields</td></tr>
<tr><td>Starting Equipment</td><td>Choose A or B: (A) Greataxe, 4 Handaxes, Explorer's Pack, and 15 GP; or (B) 75 GP</td></tr>
</table>
<h1>Becoming a Barbarian</h1>
<h2>As a Level 1 Character</h2>
<ul><li>Gain all the traits...</li></ul>
<h1>Barbarian Class Features</h1>
<h6>Barbarian Features</h6>
<table>
<tr><th>Level</th><th>Features</th></tr>
<tr><td>1</td><td>Rage</td></tr>
</table>
<p>As a Barbarian, you gain the following class features...</p>
<h3>Level 1: Rage</h3>
<p>You can imbue yourself with a primal power called Rage.</p>
<p><strong>Damage Resistance.</strong> You have Resistance to Bludgeoning.</p>
<ul>
<li>Make an attack roll against an enemy.</li>
<li>Force an enemy to make a saving throw.</li>
</ul>
<h3>Level 3: Barbarian Subclass</h3>
<p>You gain a Barbarian subclass of your choice.</p>
<h5>Barbarian Subclasses</h5>
<table>
<tr><th>Name</th></tr>
<tr><td><a href="/barbarian:path-of-the-zealot">Path of the Zealot</a></td></tr>
</table>
<h3>Level 5: Extra Attack</h3>
<p>You can attack twice instead of once.</p>
<p><a href="http://dnd2024.wikidot.com/system:page-tags/tag/class">class</a></p>
</div>
</body></html>
"""

SAMPLE_SUBCLASS_HTML = """
<html><body>
<div id="page-title">Path of the Zealot</div>
<div id="page-content">
<p>Flavor text about zealots.</p>
<h3>Level 3: Divine Fury</h3>
<p>You can channel divine power into your strikes.</p>
<h3>Level 6: Fanatical Focus</h3>
<p>Once per active Rage, if you fail a saving throw...</p>
<p><a href="http://dnd2024.wikidot.com/system:page-tags/tag/subclass">subclass</a></p>
</div>
</body></html>
"""


def run_selftests():
    failures = []

    def check(label, got, expected):
        if got != expected:
            failures.append(f"{label}\n    got:      {got!r}\n    expected: {expected!r}")

    # --- field parsers ---
    check("parse_hit_die", parse_hit_die("D12 per Barbarian level"), "d12")
    check("parse_saving_throws", parse_saving_throws("Strength and Constitution"), ["Str", "Con"])
    check(
        "parse_skill_choice",
        parse_skill_choice("Choose 2: Animal Handling, Athletics, Intimidation, Nature, Perception, or Survival"),
        (2, ["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"]),
    )
    check("parse_weapon_profs", parse_weapon_profs("Simple and Martial weapons"), ["Simple", "Martial"])
    check("parse_weapon_profs (single)", parse_weapon_profs("Simple weapons"), ["Simple"])
    check("parse_weapon_profs (none)", parse_weapon_profs("None"), [])
    check("parse_armor_profs", parse_armor_profs("Light and Medium armor and Shields"), ["Light", "Medium", "Shields"])
    check("parse_armor_profs (none)", parse_armor_profs("None"), [])
    check("singularize handaxes", singularize("Handaxes"), "Handaxe")
    check("singularize daggers", singularize("Daggers"), "Dagger")
    check(
        "parse_starting_equipment",
        parse_starting_equipment(
            "Choose A or B: (A) Greataxe, 4 Handaxes, Explorer's Pack, and 15 GP; or (B) 75 GP"
        ),
        [["Greataxe", "Handaxe", "Handaxe", "Handaxe", "Handaxe", "Explorer's Pack", "15 GP"], ["75 GP"]],
    )

    # --- full page walk, against synthetic HTML mirroring real structure ---
    soup = BeautifulSoup(SAMPLE_CLASS_HTML, "html.parser")
    pc = get_page_content(soup)
    traits, features, subclass_links = walk_page_content(pc, BASE_URL)

    check("traits keys", sorted(traits.keys()), sorted([
        "Primary Ability", "Hit Point Die", "Saving Throw Proficiencies",
        "Skill Proficiencies", "Weapon Proficiencies", "Armor Training", "Starting Equipment",
    ]))
    check("feature count", len(features), 3)
    check("feature[0] name/level", (features[0]["name"], features[0]["level"]), ("Rage", 1))
    check(
        "feature[0] description",
        features[0]["description"],
        "You can imbue yourself with a primal power called Rage.\n"
        "Damage Resistance. You have Resistance to Bludgeoning.\n"
        "Make an attack roll against an enemy.\n"
        "Force an enemy to make a saving throw.",
    )
    check("feature[1] excludes subclass table text", "Path of the Zealot" in features[1]["description"], False)
    check("feature[1] excludes table caption heading", "Barbarian Subclasses" in features[1]["description"], False)
    check(
        "feature[1] description",
        features[1]["description"],
        "You gain a Barbarian subclass of your choice.",
    )
    check("subclass_links", subclass_links, [("Path of the Zealot", f"{BASE_URL}/barbarian:path-of-the-zealot")])
    check("attacksPerLevel", compute_attacks_per_level(features), {"1": 1, "5": 2})
    check("spellcasting ability default", detect_spellcasting_ability(features), ("Int", False))
    check("stops before page-tags link", any("class" == f["description"].strip()[-5:] for f in features), False)

    sub_soup = BeautifulSoup(SAMPLE_SUBCLASS_HTML, "html.parser")
    sub_pc = get_page_content(sub_soup)
    _t, sub_features, _s = walk_page_content(sub_pc, BASE_URL)
    check("subclass feature count", len(sub_features), 2)
    check("subclass feature[0]", (sub_features[0]["name"], sub_features[0]["level"]), ("Divine Fury", 3))
    check(
        "subclass excludes flavor text before first header",
        sub_features[0]["description"].startswith("You can channel"),
        True,
    )

    if failures:
        print(f"{len(failures)} SELFTEST FAILURE(S):\n")
        for f in failures:
            print(f, "\n")
        sys.exit(1)
    else:
        print("All self-tests passed.")


if __name__ == "__main__":
    main()